<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD9c5itn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD9c5itn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerD9c5itn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerD9c5itn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerD9c5itn\appProdProjectContainer([
    'container.build_hash' => 'D9c5itn',
    'container.build_id' => '6fb7926f',
    'container.build_time' => 1612179777,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD9c5itn');
