<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\BookController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.abok9wb']) ? $this->services['service_locator.abok9wb'] : $this->load('getServiceLocator_Abok9wbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController:newAction' => function () {
    return ${($_ = isset($this->services['service_locator.yoixrmo']) ? $this->services['service_locator.yoixrmo'] : $this->load('getServiceLocator_YoixrmoService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.abok9wb']) ? $this->services['service_locator.abok9wb'] : $this->load('getServiceLocator_Abok9wbService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\BookController::newAction' => function () {
    return ${($_ = isset($this->services['service_locator.yoixrmo']) ? $this->services['service_locator.yoixrmo'] : $this->load('getServiceLocator_YoixrmoService.php')) && false ?: '_'};
}]));
